### ISSUE TITLE
binary release

### ISSUE THREAD

**Issue by glehmann** [virtualtam/ccache_exporter#1]
Could you make a binary release, at least for the usual x86_64 architecture?
I may contribute a travis build if you're interested!

**Comment by virtualtam** [comment]
Hey @glehmann, and sorry this issue fell under the radar :)

I'm currently reworking this repository, added a Travis setup to run tests, and plan to automate cross-platform binary release generation with [prometheus/promu](https://github.com/prometheus/promu).

**Comment by virtualtam** [comment]
Cross-platform builds and binary releases have been added in [v2.0.0](https://github.com/virtualtam/ccache_exporter/releases/tag/v2.0.0), with amd64 builds for Darwin (Mac OS), Linux and Windows as a starting point, feel free to give them a spin (I've tested the Linux and Windows binaries so far) :)
